### ISSUE TITLE
Hangs After Clicking "Launch Rewind!"

### ISSUE THREAD

**Issue by AwkwardTurtle42** [Chaphasilor/jellyfin-rewind#11]
I was able to connect Jellyfin Rewind to my jelly, and followed the prompts to install the reporting plugin and restart server. The loading bar filled, and when I clicked "Launch Rewind!" it full screened with a black background, but then hung and did nothing else. 

I've tried this on both Firefox and a Chromium browser, and had another user test (on the same jellyfin server) with the same results.

**Comment by Chaphasilor** [comment]
Hmm, intersting.  
Firstly, this year's rewind is not ready yet, I'll release it at December 31st like every year. So the results with last year's version won't be acurate anyway, especially if you didn't have the Playback Reporting plugin installed before.

Can you try opening your browser's developer console (usually by pressing F12), and then reloading and trying again? There you should be able to see any errors that are thrown. A screenshot of these console with errors would probably be enough.  
I actually haven't tested with Jellyfin 10.10 yet, so it could be that there are some changes that I need to handle.

Also, which server version are you using?

**Comment by Nik-mmzd** [comment]
Jellyfin 10.10.3, selfhosted Rewind from official docker image, got no issues.

Offtopic: can you make docker image accept year as env variable to be able to launch your own selfhosted rewind without waiting till December, 31? Also, it'll be a good feature to be able to link selfhosted Rewind installation to specific Jellyfin server.

**Comment by RiccardoUva** [comment]
these are the errors i'm getting:  

GET https://[my server]/Plugins 403 (Forbidden)
checkIfPlaybackReportingInstalled @ index-BTAs-5ua.js:9
St @ index-BTAs-5ua.js:1313
Jn @ index-BTAs-5ua.js:1282
await in Jn
includes.t @ index-BTAs-5ua.js:1375
s.push.Object.assign.e @ index-BTAs-5ua.js:1Understand this errorAI
index-BTAs-5ua.js:1313 Failed to check the playback reporting setup, continuing without it: SyntaxError: Failed to execute 'json' on 'Response': Unexpected end of JSON input
    at Ld.checkIfPlaybackReportingInstalled (index-BTAs-5ua.js:9:14247)
    at async St (index-BTAs-5ua.js:1313:103)

Couldn't save full report to localStorage (maybe quota exceeded?). Saving a subset only




\/ this error comes up every time i click "launch rewind!" \/

index-BTAs-5ua.js:1057 Uncaught TypeError: Cannot read properties of undefined (reading 'target')
    at Zb (index-BTAs-5ua.js:1057:47)
    at index-BTAs-5ua.js:1054:22
    at s.push.Object.assign.e (index-BTAs-5ua.js:1:3778)
    at o (index-BTAs-5ua.js:1:3356)
    at Oi (index-BTAs-5ua.js:1:3565)
    at ed (index-BTAs-5ua.js:1:5197)
    at Fi (index-BTAs-5ua.js:1:4248)
    at Fi (index-BTAs-5ua.js:1:4314)
    at Fi (index-BTAs-5ua.js:1:4314)
    at r (index-BTAs-5ua.js:1:5860)

**Comment by Chaphasilor** [comment]
@Nik-mmzd good to hear, but please open separate issues for your requests to facilitate discussion

@RiccardoUva @AwkwardTurtle42 thanks for the error logs, I'll take a look later! Seems like a simple fix.  
Are you using the website or docker image?

**Comment by RiccardoUva** [comment]
I'm using the website, the https version

**Comment by Chaphasilor** [comment]
Okay, thanks for reporting this bug. It wasn't super easy to figure out, seems like a dependency update had an unintended effect.  
I've reverted it and everything should be working now.

However, I did set up a placeholder page for now, since the version for 2024 is not done yet, and the version on the website is still configured for 2023 (so the results won't be accurate). That means you'll need to wait a few more weeks before you can get started. I'm not sure why Spotify always launches their rewind so early (although I feel like they keep releasing it later each year), since we're missing out on some stats this way.  
I hope you understand.

But your report did help me catch this bug before everything got released, so thank you for that!
