### ISSUE TITLE
Sorry, we couldn't generate your Rewind Report.

### ISSUE THREAD

**Issue by lichenophile** [Chaphasilor/jellyfin-rewind#6]
Hello, I stumbled across #4 to see if I could solve my problem getting Rewind working on my local only Jellyfin instance (http only also). But both the included sites in this repos readme, and the locally run version you have provided here end up with the following result:

![image](https://github.com/Chaphasilor/jellyfin-rewind/assets/67679349/1e3a3217-4153-4c28-b23c-9bc8fefeb00a)

Any help would be muchly appreciated!

**Comment by Chaphasilor** [comment]
Hi @lichenophile!

I'm sorry to hear that. Could you open your browsers developer tools (probably by pressing F12 or Ctrl + Shift + i) and then retry with the debug console open? Seeing the logs and actual errors would help immensely with figuring things out!

Also, could you please share some information about your environment? For example:

- Browser and version
- Jellyfin server version
- Your Jellyfin server's network setup
  - Are you connecting via a local IP (e.g. `192.168.x.y`), a local domain name (e.g. `jellyfin.local`), ~~a public domain/IP without HTTPS, a public domain/IP with a self-signed HTTPS certificate, etc.~~
- Which instances of Jellyfin Rewind did you try?
  - You mentioned the http-only version, so http://jellyfin-rewind-http.chaphasilor.xyz ?
  - If you also set up the version I built in #4, how are you hosting and accessing it? Which web server, and at which address are you accessing it?
- Is your Jellyfin user an admin account?
- Do you have the "Playback Reporting" plugin installed?

I hope I can figure out the issue!

**Comment by Chaphasilor** [comment]
Thanks for the detailed logs and investigation.

Okay, it's definitely not a network issue. Playback Reporting installation seems fine, but for some reason it's not loading any of your media, neither from Playback Reporting nor from Jellyfin itself. Not sure what's going on, but it could be an issue with the music libraries.

You could try creating a new account and giving it access to only your music library, and then trying again. That should at least show *some* data, unless there is something fundamentally different about your setup...

**Comment by Chaphasilor** [comment]
Haha yeah maybe I should make it more obvious, could be that it's not clear until you actually get to the Rewind, so it's understandable that you were confused! Sorry about that...

Support for other media types has been requested last year already and is on my ToDo-list, but I simply didn't have the time for that yet. Maybe next year? Maybe I could build two separate apps in parallel, one for music and one for movies and shows?

Either way, this year only music is supported, sadly :(
